if: tag IS blank # Don't build tags

dist: xenial
language: go
go:
  - "1.13"
env:
  - GO111MODULE="on" DOCKER_CLI_EXPERIMENTAL="enabled"
addons:
  apt:
    packages:
      - docker-ce
before_install:

jobs:
  include:
    - stage: test
      script:
        - make
    - stage: docker-prep
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sudo docker run --privileged linuxkit/binfmt:v0.6
    - stage: deploy-image-dev
      script:
        - make
        - make docker docker-push DOCKER_VERSION_ADDTL=-develop
    - stage: deploy-image
      script:
        - make
        - bash <(curl -s https://codecov.io/bash) -f /tmp/app.cover
        - make docker docker-push tag tag-push
stages:
  - name: test
    if: type = pull_request OR (type = push AND branch != master)
  - name: docker-prep
    if: (type = push AND branch = develop) OR (type = push AND branch = master)
  - name: deploy-image-dev
    if: type = push AND branch = develop
  - name: deploy-image
    if: type = push AND branch = master
